---
- name: "Layer 2: Host Networking & DNS"
  hosts: all
  become: true

  tasks:
    - name: Install systemd-resolved
      apt:
        name: systemd-resolved
        state: present
        update_cache: false

    - name: Disable DNSStubListener to free up Port 53
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^#?DNS=', line: 'DNS=10.0.0.245 1.1.1.1' }
        - { regexp: '^#?DNSStubListener=', line: 'DNSStubListener=no' }
        - { regexp: '^#?LLMNR=', line: 'LLMNR=no' }
      notify: Restart resolved

    - name: Use the static resolv.conf (Required when Stub is off)
      file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: true

  handlers:
    - name: Restart resolved
      systemd:
        name: systemd-resolved
        state: restarted
        enabled: true
