---
- name: "Deploy Homelab Stack"
  hosts: all
  become: true

  roles:
    - role: storage
      tags: storage

    - role: base
      tags: base

    - role: networking
      tags: networking

    - role: security
      tags: security

    - role: docker
      tags: docker

    - role: caddy
      tags: caddy

    - role: pihole
      tags: pihole

    - role: nextcloud
      tags: nextcloud

    - role: mealie
      tags: mealie

    - role: jellyfin
      tags: jellyfin

  post_tasks:
    - name: Deploy Master Docker Compose Orchestrator
      ansible.builtin.template:
        src: roles/docker/templates/master-compose.yml.j2
        dest: "{{ docker_config_path }}/docker-compose.yml"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: '0644'
      tags: always
