# General configuration for all hosts
hostname_desired: "homelab"
timezone: "America/Los_Angeles" # CHANGE TO YOUR TIMEZONE
domain: "homelab.local" # CHANGE TO YOUR DOMAIN NAME
admin_user: "sysadmin"
dns_servers:
  - "10.0.0.245"
  - "1.1.1.1"

# Application Feature Flags
enable_nextcloud: false
enable_mealie: false
enable_jellyfin_stack: true

# Subdomains
nextcloud_subdomain: "cloud"
mealie_subdomain: "mealie"
jellyfin_subdomain: "jellyfin"
jellyseerr_subdomain: "request"
wizarr_subdomain: "join"

# Docker/User config
puid: 1000
pgid: 1000
docker_project_name: "homelab"
docker_config_path: "/home/{{ admin_user }}/docker_configs"

# Storage configurations
storage_root: "/storage"
base_storage_path: "{{ storage_root }}/jellyfin/data"
format_disks: true
disk_1_source: "/dev/sdb"
disk_2_source: "/dev/sdc"

# Service configurations
vpn_region: "CA Vancouver" # May need to change if you encounter connectivity issues.
pihole_web_port: 8080
nextcloud_web_port: 8081
mealie_web_port: 9000
qbittorrent_webui_port: 8082
jellyfin_port: 8096
jellyseerr_port: 5055
prowlarr_port: 9696
radarr_port: 7878
sonarr_port: 8989
wizarr_port: 5690
newtarr_port: 9705
bazarr_port: 6767

# Vault Secrets
pihole_password: "{{ vault_pihole_password | mandatory('Set vault_pihole_password in your vault file.') }}"
pia_user: "{{ vault_pia_user | mandatory('Set vault_pia_user in your vault file.') }}"
pia_pass: "{{ vault_pia_pass | mandatory('Set vault_pia_pass in your vault file.') }}"
