---
- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Create directory for Docker GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Docker GPG apt Key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present

- name: Add LazyDocker GPG key
  ansible.builtin.get_url:
    url: https://debian.griffo.io/EA0F721D231FDD3A0A17B9AC7808B4DD62C41256.asc
    dest: /tmp/lazydocker.asc

- name: Dearmor LazyDocker GPG key
  ansible.builtin.shell: gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/debian.griffo.io.gpg /tmp/lazydocker.asc
  args:
    creates: /etc/apt/trusted.gpg.d/debian.griffo.io.gpg

- name: Add LazyDocker Repository
  ansible.builtin.apt_repository:
    repo: "deb https://debian.griffo.io/apt {{ ansible_distribution_release }} main"
    filename: debian.griffo.io
    state: present

- name: Install Docker Engine, Compose, and LazyDocker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - lazydocker
    update_cache: yes
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Add admin user to docker group
  ansible.builtin.user:
    name: "{{ admin_user }}"
    groups: docker
    append: yes

- name: Verify Docker is responding
  ansible.builtin.command: docker info
  changed_when: false
  register: docker_info
  failed_when: docker_info.rc != 0

- name: Ensure Docker configuration root directory exists
  ansible.builtin.file:
    path: "{{ docker_config_path }}"
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: '0775'

- name: Create shared Docker network
  community.docker.docker_network:
    name: caddy_net
    state: present
