---
- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ hostname_desired }}"

- name: Fix /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127.0.0.1'
    line: "127.0.0.1 localhost {{ hostname_desired }}"
    owner: root
    group: root
    mode: '0644'

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Update apt cache and upgrade all packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600

- name: Install minimal admin tools
  ansible.builtin.apt:
    name:
      - neovim
      - htop
      - btop
      - curl
      - tree
      - fastfetch
    state: present

- name: Set Neovim as default editor
  ansible.builtin.alternatives:
    name: editor
    path: /usr/bin/nvim

- name: Remove unnecessary packages
  ansible.builtin.apt:
    autoremove: yes
    purge: yes
