---
- name: Check if Pi-hole directory exists
  ansible.builtin.stat:
    path: "{{ docker_config_path }}/pihole"
  register: pihole_dir

- name: Tear down Pi-hole Stack
  community.docker.docker_compose_v2:
    project_src: "{{ docker_config_path }}/pihole"
    files: ["docker-compose.yml"]
    project_name: "{{ docker_project_name }}"
    state: absent
  environment:
    COMPOSE_IGNORE_ORPHANS: "true"
  when: pihole_dir.stat.exists

- name: Remove UFW rules for Pi-hole
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    state: absent
  loop:
    - { port: "53", proto: "tcp" }
    - { port: "53", proto: "udp" }
